--drop table ADMIN.PROJECT_NHANSU;
create table PROJECT_NHANSU(
    MANV varchar2(5),
    HOTEN VARCHAR2(100),
    PHAI VARCHAR(10),
    NGSINH DATE,
    PHUCAP NUMBER,
    DT VARCHAR(12),
    VAITRO VARCHAR2(40),
    DONVI varchar2(5),
    PRIMARY KEY(MANV)
);
--drop table ADMIN.PROJECT_SINHVIEN;
create table PROJECT_SINHVIEN(
    MASV varchar2(5),
    HOTEN VARCHAR(100),
    PHAI VARCHAR(10),
    NGSINH DATE,
    DIACHI VARCHAR(200),
    DT VARCHAR(12),
    MACT varchar2(10),
    MANGANH NUMBER,
    SOTCTL NUMBER,
    DTBTL FLOAT,
    PRIMARY KEY(MASV)
);
--drop table ADMIN.PROJECT_DONVI;
create table PROJECT_DONVI(
    MADV varchar2(5),
    TENDV VARCHAR(200),
    TRGDV varchar2(5),
    PRIMARY KEY(MADV)
);

ALTER TABLE PROJECT_NHANSU ADD CONSTRAINT FK_NHANSU_DONVI FOREIGN KEY(DONVI) REFERENCES PROJECT_DONVI(MADV);
--drop table ADMIN.PROJECT_HOCPHAN;
create table PROJECT_HOCPHAN (
    MAHP varchar2(5),
    TENHP VARCHAR(200),
    SOTC NUMBER,
    STLT NUMBER,
    STTH NUMBER,
    SOSVTD NUMBER,
    MADV varchar2(5),
    PRIMARY KEY(MAHP)
);

ALTER TABLE PROJECT_HOCPHAN ADD CONSTRAINT FK_HOCPHAN_DONVI FOREIGN KEY(MADV) REFERENCES PROJECT_DONVI(MADV);
--drop table ADMIN.PROJECT_KHMO;
create table PROJECT_KHMO(
    MAHP varchar2(5),
    HK NUMBER,
    NAM NUMBER,
    MACT VARCHAR(10),
    PRIMARY KEY(MAHP,HK,NAM,MACT)
);

ALTER TABLE PROJECT_KHMO ADD CONSTRAINT FK_KHMO_HOCPHAN FOREIGN KEY(MAHP) REFERENCES PROJECT_HOCPHAN(MAHP);
--drop table ADMIN.PROJECT_PHANCONG;
create table PROJECT_PHANCONG(
    MAGV varchar2(5),
    MAHP varchar2(5),
    HK NUMBER,
    NAM NUMBER,
    MACT VARCHAR(10),
    PRIMARY KEY(MAGV,MAHP,HK,NAM,MACT)
);

ALTER TABLE PROJECT_PHANCONG ADD CONSTRAINT FK_PHANCONG_NHANSU FOREIGN KEY(MAGV) REFERENCES PROJECT_NHANSU(MANV);
ALTER TABLE PROJECT_PHANCONG ADD CONSTRAINT FK_PHANCONG_KHMO FOREIGN KEY(MAHP,HK,NAM,MACT) REFERENCES PROJECT_KHMO(MAHP,HK,NAM,MACT);

--drop table ADMIN.PROJECT_DANGKI;
create table PROJECT_DANGKI(
    MASV varchar2(5),
    MAGV varchar2(5),
    MAHP varchar2(5),
    HK NUMBER,
    NAM NUMBER,
    MACT VARCHAR(10),
    DIEMTH FLOAT,
    DIEMQT FLOAT,
    DIEMCK FLOAT,
    DIEMTK FLOAT,
    
    PRIMARY KEY(MASV,MAGV,MAHP,HK,NAM,MACT)
);

ALTER TABLE PROJECT_DANGKI ADD CONSTRAINT FK_DANGKI_KHMO FOREIGN KEY(MAHP,HK,NAM,MACT) REFERENCES PROJECT_KHMO(MAHP,HK,NAM,MACT);
ALTER TABLE PROJECT_DANGKI ADD CONSTRAINT FK_DANGKI_NHANSU FOREIGN KEY(MAGV) REFERENCES PROJECT_NHANSU(MANV);
ALTER TABLE PROJECT_DANGKI ADD CONSTRAINT FK_DANGKI_SINHVIEN FOREIGN KEY(MASV) REFERENCES PROJECT_SINHVIEN(MASV);